<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    public function up(): void
    {
        Schema::create('orders', function (Blueprint $table) {
            $table->id();
            $table->string('order_number', 24)
                  ->comment('Human-facing, e.g. GH-2608-0001427. Generated by OrderNumberGenerator.');
            $table->ulid('public_token')->comment('Unguessable key for guest order-tracking URLs.');

            $table->foreignId('user_id')->nullable()->constrained()->nullOnDelete();
            $table->foreignId('cart_id')->nullable()->constrained()->nullOnDelete();

            // Contact snapshot — guests have no user row
            $table->string('email', 180);
            $table->string('phone', 20);
            $table->string('customer_name', 200);

            $table->string('status', 24)->default('pending')
                  ->comment('App\Enums\OrderStatus: pending|confirmed|shipped|delivered|cancelled|refunded');
            $table->string('payment_status', 24)->default('pending')
                  ->comment('App\Enums\PaymentStatus: pending|awaiting_verification|paid|partially_refunded|refunded|failed');

            $table->char('currency', 3)->default('PKR');
            $table->unsignedBigInteger('subtotal_amount')->default(0);
            $table->unsignedBigInteger('discount_amount')->default(0);
            $table->unsignedBigInteger('shipping_amount')->default(0);
            $table->unsignedBigInteger('cod_fee_amount')->default(0);
            $table->unsignedBigInteger('tax_amount')->default(0);
            $table->unsignedBigInteger('grand_total_amount')->default(0);
            $table->unsignedBigInteger('paid_amount')->default(0);
            $table->unsignedBigInteger('refunded_amount')->default(0);

            $table->foreignId('coupon_id')->nullable()->constrained()->nullOnDelete();
            $table->string('coupon_code', 40)->nullable();

            $table->string('payment_method', 40)
                  ->comment('Payment driver key: cod|bank_transfer|jazzcash|easypaisa. See §6.');
            $table->foreignId('shipping_rate_id')->nullable()->constrained()->nullOnDelete();
            $table->string('shipping_method_name', 120)->nullable();

            $table->string('tracking_number', 80)->nullable();
            $table->string('courier', 60)->nullable();
            $table->string('tracking_url', 512)->nullable();

            $table->text('customer_note')->nullable();
            $table->text('admin_note')->nullable();
            $table->string('cancel_reason', 255)->nullable();

            $table->timestamp('placed_at')->nullable();
            $table->timestamp('confirmed_at')->nullable();
            $table->timestamp('shipped_at')->nullable();
            $table->timestamp('delivered_at')->nullable();
            $table->timestamp('cancelled_at')->nullable();
            $table->timestamp('refunded_at')->nullable();

            $table->string('ip_address', 45)->nullable();
            $table->string('user_agent', 512)->nullable();
            $table->json('utm')->nullable()->comment('{"source":"facebook","medium":"cpc","campaign":"eid-2026"}');

            $table->timestamps();
            $table->softDeletes();

            $table->unique('order_number', 'orders_order_number_unique');
            $table->unique('public_token', 'orders_public_token_unique');
            $table->index(['status', 'created_at'], 'orders_status_created_index');
            $table->index(['payment_status', 'created_at'], 'orders_payment_status_created_index');
            $table->index(['user_id', 'created_at'], 'orders_user_created_index');
            $table->index('email', 'orders_email_index');
            $table->index('phone', 'orders_phone_index');
            $table->index(['payment_method', 'status'], 'orders_method_status_index');
        });
    }

    public function down(): void { Schema::dropIfExists('orders'); }
};
